version: '3.1'


services:
  stats-server:
    build: statistics
    container_name: explore-with-me-statistics
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore_with_me_stats
      - SPRING_DATASOURCE_USERNAME=explore_with_me_admin
      - SPRING_DATASOURCE_PASSWORD=qscesz
    networks:
      - ewm-stats
      - web

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore_with_me_stats
      - POSTGRES_USER=explore_with_me_admin
      - POSTGRES_PASSWORD=qscesz
    networks:
      - ewm-stats

  ewm-service:
    build: main
    container_name: explore-with-me-main
    ports:
      - "8080:8080"
    expose:
      - "9090"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STATS_SERVER=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore_with_me_db
      - SPRING_DATASOURCE_USERNAME=explore_with_me_admin
      - SPRING_DATASOURCE_PASSWORD=qscesz
    networks:
      - web
      - ewm-main

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore_with_me_db
      - POSTGRES_USER=explore_with_me_admin
      - POSTGRES_PASSWORD=qscesz
    networks:
      - ewm-main

networks:
  ewm-main:
    driver: bridge
  ewm-stats:
    driver: bridge
  web:
    driver: bridge