CREATE TABLE IF NOT EXISTS hit
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    app        VARCHAR(255),
    ip         VARCHAR(32),
    created_on TIMESTAMP,
    uri        VARCHAR(1024)
);